In [8]:
import pandas as pd 


# Criar um data frama(trazer os dadaos para a memória do python)

df = pd.read_csv('dados.csv')

display(df)

       marca       modelo     cor   ano   valor
0         VW        Fusca  Branco  1985   25000
1  Chevrolet        Opala   Preto  1970   52500
2       FIat        Marea   Preto  2001   15680
3         VW  Variante II  Branco  1971    5800
4  Chevrolet     Chevette    Bege  1985   10000
5        BMW         320i   Prata  2017   80620
6      Honda        Civic   Prata  2023  140000

In [15]:
#head imprime apenas uma amostra dos dados
print(df.head(2))

print()

#info
print(df.info())
      
print('\n')
    
print(df.describe())

print('\n')

print(df.shape)

print(df.columns)

       marca modelo     cor   ano  valor
0         VW  Fusca  Branco  1985  25000
1  Chevrolet  Opala   Preto  1970  52500

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   marca   7 non-null      str
 1   modelo  7 non-null      str
 2   cor     7 non-null      str
 3   ano     7 non-null      int64
 4   valor   7 non-null      int64
dtypes: int64(2), str(3)
memory usage: 412.0 bytes
None


               ano          valor
count     7.000000       7.000000
mean   1993.142857   47085.714286
std      21.137869   48889.135418
min    1970.000000    5800.000000
25%    1978.000000   12840.000000
50%    1985.000000   25000.000000
75%    2009.000000   66560.000000
max    2023.000000  140000.000000


(7, 5)
Index(['marca', 'modelo', 'cor', 'ano', 'valor'], dtype='str')

In [21]:
# Consultar apneas uma coluna
marca = df['marca']

print(marca)

print('\n')

#consulta direto no print
print(df['modelo'])

#Consultar mais que uma coluna 
marca_modelo_cor = df[['marca','modelo','cor']]

display(marca_modelo_cor)

0           VW
1    Chevrolet
2         FIat
3           VW
4    Chevrolet
5          BMW
6        Honda
Name: marca, dtype: str


0          Fusca
1          Opala
2          Marea
3    Variante II
4       Chevette
5           320i
6          Civic
Name: modelo, dtype: str

       marca       modelo     cor
0         VW        Fusca  Branco
1  Chevrolet        Opala   Preto
2       FIat        Marea   Preto
3         VW  Variante II  Branco
4  Chevrolet     Chevette    Bege
5        BMW         320i   Prata
6      Honda        Civic   Prata

In [23]:
# Criar filtros

# Quero saber quantos carros não pagam mais ipva no meu estoque

noIpva = df[df['ano'] < 2006 ]

display(noIpva)

       marca       modelo     cor   ano  valor
0         VW        Fusca  Branco  1985  25000
1  Chevrolet        Opala   Preto  1970  52500
2       FIat        Marea   Preto  2001  15680
3         VW  Variante II  Branco  1971   5800
4  Chevrolet     Chevette    Bege  1985  10000

In [27]:
# Apresente os carros que custam mais que R$20.000

Carrosmaiscaros = df[df['valor'] > 20000]

display(Carrosmaiscaros)

# Apresente apenas os carros da chevrolet

carrosGM = df[df['marca'] == 'Chevrolet']

display(carrosGM)

       marca modelo     cor   ano   valor
0         VW  Fusca  Branco  1985   25000
1  Chevrolet  Opala   Preto  1970   52500
5        BMW   320i   Prata  2017   80620
6      Honda  Civic   Prata  2023  140000

       marca    modelo    cor   ano  valor
1  Chevrolet     Opala  Preto  1970  52500
4  Chevrolet  Chevette   Bege  1985  10000